### ISSUE TITLE
(back burner) Simplify commands

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#10]
Goal: reduce amount of typing needed.

Ideas:
- dates expressed as reference to now: e.g. +2d for two days in the future

**Comment by andyl** [comment]
I added a DSL for offer maturation dates (see #17).  

At some point we'll need GraphQL for flexibility (see #29) 

`offer create_counter` and `offer take` simplify things quite a bit.  

Post suggestions if you have other ideas!
