### ISSUE TITLE
Non graceful error handling

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#11]
The following command resulted in non-graceful error handling

> bmx offer cross 2bcbbcb0-41cd-48e6-b328-1cd837fecc15

I realized, that the **cross** command is with *contract* -> I find it more logical to cross an *offer* which results in a *contract*.

    ERROR: "bmx offer help" was called with arguments ["cross", "2bcbbcb0-41cd-48e6-b328-1cd837fecc15", "--commit-type=expand"]
    Usage: "bmx offer help [COMMAND]"
    Traceback (most recent call last):
            12: from /home/deploy/.gem/ruby/2.5.0/bin/bmx:23:in `<main>'
            11: from /home/deploy/.gem/ruby/2.5.0/bin/bmx:23:in `load'
            10: from /home/deploy/.gem/ruby/2.5.0/gems/bmx_cl_ruby-0.1.0/bin/bmx:5:in `<top (required)>'
             9: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
             8: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
             7: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
             6: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
             5: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
             4: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
             3: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
             2: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
             1: from /home/deploy/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    /home/deploy/.gem/ruby/2.5.0/gems/bmx_cl_ruby-0.1.0/lib/cmd/contract.rb:9:in `list': uninitialized constant BmxApiRuby::ContractsApi (NameError)
    Did you mean?  BmxApiRuby::ContractApi
    Traceback (most recent call last):
      File "buy_bot.py", line 77, in <module>
        contracts = json.loads(check_output(["bmx", "contract", "list"])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['bmx', 'contract', 'list']' returned non-zero exit status 1

**Comment by andyl** [comment]
Yeah - this is a systematic problem.

**Comment by andyl** [comment]
Subsumed by #28
