### ISSUE TITLE
New command: "offer match"

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#12]
The idea is that I can match an existing offer without having to copy out the issue, price, volume, and maturation.

> bmx offer match UUID

Expected behavior is to create the matching offer on the other side.

**Comment by GeorgLink** [comment]
low priority, I can mimic this behavior with a workaround

**Comment by andyl** [comment]
Added new commands:
- offer create_clone
- offer create_counter
- offer take (creates a counter and crosses, all in one step)
