### ISSUE TITLE
Standardize format for maturation date

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#17]
When creating an offer, I must provide the maturation date in (YYMMDD_HHMM)
When I look at "bmx offer show", however, maturation date is formatted (%Y-%m-%dT%H%M%s%z)

This means, I cannot take offer[maturation_beg] and use it to create a new offer (match an offer; related #12)

Ideally, I want to be able to use the returned maturation date from an existing offer and use it as an input, without conversion, for a new offer.

PS: what is the difference between 'maturation_beg' and 'maturation_end' ? I did not specify a 2-day window -> confusing for user.

**Comment by andyl** [comment]
Firstly, "host info" now takes a "strftime" option.

Secondly, there is now a DSL for specifying offer maturation dates.

`--maturation_offset=<statement>`

A statement can be done of: 
- `minutes_<N>`, `hours_<N>`, `days_<N>`, `weeks_<N>`, `months_<N>`
- end_of_today, end_of_tomorrow
- end_of_hour_<N>, end_of_day_<N>, end_of_week_<N>, end_of_month_<N>
