### ISSUE TITLE
add information to "bmx contract show" 

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#19]
The API call "bmx contract show"  currently only returns the 'uuid'.

I would like to see:
- statement (plain text)
- maturation date
- positions (uuids or objects with additional information)
- escrows (unless that is included in positions)

**Comment by andyl** [comment]
- added statement and maturation date
- added counts for positions, escrows, and amendments
- added commands "contract positions", "contract amendments", "contract escrows"
- added commends "position list", "position show"
- added commands "escrow list", "escrow show"
- added commands "amendment list", "amendment show"
