### ISSUE TITLE
error 404 on "bmx user show"

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#21]
I get an error on "bmx user show". 

I am debugging and wanted to see what positions a user has.

**Comment by GeorgLink** [comment]
"bmx user show UUID"

is missing

**Comment by andyl** [comment]
This was a little funky.  When I tried it, I ran into problems with bash interpreting/strippping the '.' in the email address.  Now it uses a UUID instead of email address.
