### ISSUE TITLE
add expand regression test to test for FIXED and UNFIXED resolve

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#22]
If I read the regression test correctly, it does not cover the FIXED and UNFIXED case:
https://github.com/bugmark/bmx_cl_ruby/blob/master/spec/contract_resolve_spec.rb

Suggestion: make sure to test for both cases.

**Comment by andyl** [comment]
I can promise that at this point, there are very very many untested paths in the code.  I've got some refactoring to do on the `resolve` function (right now it's not generating an event...)  will update this issue when my changes are complete.

**Comment by andyl** [comment]
Fixed.
