### ISSUE TITLE
add issue status information to "bmx issue show"

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#23]
When looking at an issue,  I would expect to see whether an issue was already fixed or not. 

maybe even contain the information, for when the issue was last updated, to have a sense for how reliable the status information is.

Suggestion: add to "bmx show issue"
- status = fixed or unfixed
- status_updated = datetime when status was last changed
- contracts formed for this issue (default: open contracts; optional: matured contracts)

**Comment by andyl** [comment]
1) status is shown in field "stm_status" ('statement status')
2) we now show the field 'updated_at'
3a) added the field 'num_contracts' to `issue show`
3b) added a new command `issue contracts` to show contract detail
