### ISSUE TITLE
change default for maturation to be single point in time only

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#25]
Current behavior is for an offer to get a maturation date range even though the trader only specified a single date.

A date range should only be created if specified by the trader. The default is to only create a single point in time maturation date if nothing else is specified.

**Comment by andyl** [comment]
Behind the scenes, we want offers to have date-range to increase likelihood of offer matching. (we do an `overlap` search...)

When you make an offer with a single date(time), we construct a start/end range which is (`date-1.day` .. `date+1.day`) 

Note that there is a couple methods defined on `Offer`
- `maturation_range` gives the start/finish range
- `maturation` gives the average of the maturation range (ie the original maturation date)
