### ISSUE TITLE
Error in 'bmx repo show'

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#5]
I checked the REPO_UUID several times.

For error, see screenshot:
![image](https://user-images.githubusercontent.com/8862021/35253917-72346030-ffad-11e7-80ea-1351d7357921.png)

**Comment by andyl** [comment]
Fixed - many thanks for this report.

**Comment by GeorgLink** [comment]
I confirm that it works now :-)
