### ISSUE TITLE
contract resolve does not consider the status of a bug

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#52]
Regardless of whether I set the status of a bug to "closed" or "open", upon 'bmx contract resolve', the same position gets the payout.

How to repeat this issue?
Run trivial bot and change the status of an issue (try both: closed and open) before resolving issues. The payout will always go to the same position holder, which is not the expected behavior.

**Comment by GeorgLink** [comment]
Regression test added: #54 

#53 is an interesting idea, but less important to bot writing right now than: 
- [ ] #27
- [ ] #35
- [ ] #46
- [ ] #55 
- [ ] #57
- [ ] #58

**Comment by andyl** [comment]
Thanks for the PRs with the failing specs.

All CL specs now passing.

**Comment by GeorgLink** [comment]
Thank you!
​
