### ISSUE TITLE
add information to "issue show"

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#55]
"bmx issue show" should show me the following information:

- [x] what is the current status of the issue (closed/open)
- [ ] what are the open offers on this issue (list of uuids)
- [ ] what are the unresolved contracts on this issue (list of uuids)

**Comment by andyl** [comment]
`stm_status` has the current issue status

`bmx issue offers` > show current offers

`bmx issue contracts` > show current contracts
