### ISSUE TITLE
add information to "contract show"

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#57]
When I look at a contract, I want to know more information:

- [x] add positions on this contract (list of position uuids)
- [x] add escrows on this contract (list of escrow uuids)
- [x] add sum tokens in escrow for this contract (integer)
- [x] status of underlying statement (fixed or unfixed)

**Comment by andyl** [comment]
`bmx contract show` now displays:
- sum of escrow value (`total_value`)
- current awardee status (`awardee` => "fixed|unfixed")

You now have two commands: `bmx contract positions` and `bmx contract escrows`.  Note that you can use the local cache to avoid cutting/pasting contract uuids:
> `bmx contract list`   #> caches the results
> `bmx contract positions cached_contracts_uuid_first`  #> shows positions
> `bmx contract escrows cached_contracts_uuid_first`  #> shows escrows

**Comment by GeorgLink** [comment]
​Thank you.
