### ISSUE TITLE
error on 'contract positions'

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#62]
`bmx contract positions` throws an error if given a valid contract uuid.

**Comment by andyl** [comment]
Fixed.

**Comment by GeorgLink** [comment]
Thanks Andy,

How do I update the research server again?

**Comment by andyl** [comment]
Per my slack comment - let me know if you want me to push the server code ASAP.

To install or update the ruby bindings and CL-bmx, go to `bmx_bots` and use the script `bootstrap.sh`.

Usually the server and client should be updated at the same time to keep everything in sync.

**Comment by GeorgLink** [comment]
Tthank you. No hurry. I just went to test the API call and remembered that
the server needs to be updated first.

**Comment by GeorgLink** [comment]
I ran `bootstrap.sh` in the `bmx_bots` folder but the error continues to exist. Do I need to do something else to update bugmark?

**Comment by andyl** [comment]
Yes the server and client should be updated at the same time.  I'll push the server in the next 10-15 mins and ping you on slack when it's ready to go.

**Comment by GeorgLink** [comment]
I see.
Maybe we will talk about this later: Is there a script that Malvika and I
can run to update the server and client?

**Comment by andyl** [comment]
Could be done yeah.  Let's discuss.
