### ISSUE TITLE
Setup IRC for Bugmark Developers

### ISSUE THREAD

**Issue by andyl** [bugmark/bmx_cl_ruby#63]
We could really use an IRC for real-time chat for Bugmark developers!  Candidates for chat software are:
- IRC
- Slack
- Discourse
- Other? (list below)

Tasks:
- [x] coordinate with andy re: plan of action
- [x] be involved with the discussion re: prioritization and selection
- [x] implement the solution (IRC or Slack probably...)
- [x] document account information & management procedures

**Comment by snehasi** [comment]
@andyl -
Cool. I'd like to work on this.

**Comment by GeorgLink** [comment]
+2 https://www.discourse.org/
+1 IRC

​

**Comment by andyl** [comment]
@snehasi that's great - does the task list I outlined look ok?

**Comment by snehasi** [comment]
@andyl -
Yes, the list's good.
I think good integrations for automations, file sharing and efficient notification controls would be the most important other features we should have in the real time chat.

**Comment by andyl** [comment]
@snehasi ok fine then the next action is to select IRC software.  

@GeorgLink I'm a big fan of Discourse, but to me it's not a fit because it's not real-time chat.  I'd like to add Discourse at some point in the future, when our community grows to 100 members or so.  

For live chat, I use Slack for everything else these days, so I prefer Slack over IRC.

**Comment by GeorgLink** [comment]
​Do you need to invite people to the Slack channel? I could not join just
now.

**Comment by andyl** [comment]
@snehasi and @GeorgLink both of you are now admins on bugmark.slack.com.  I will close this issue and make it a habit to leave the slackroom open when I am available to chat.

**Comment by GeorgLink** [comment]
​Thanks!

**Comment by snehasi** [comment]
Thanks.
