### ISSUE TITLE
command to retrieve and set system time

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/bmx_cl_ruby#9]
For the simulation, we need a way to retrieve and set system time.

**Comment by andyl** [comment]
Here's a few things:
1) `host info` gives the system time and takes a `strftime` option
2) `host increment_day_offset` moves system time forward
3) `host increment_hour_offset` moves system time forward
4) `host rebuild --with_offset_days=<N>` lets you start the system clock in the past or future
